name: Node.js CI
on:
    push: 
        branches: 
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.0,17.0,18.x,]
