# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
    - name: Get NPM cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)" 
    - name: Cache NPM
      uses: actions/cache@v4.2.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{ steps.npm-cache.outputs.dir }}
        # An explicit key for restoring and saving the cache
        key: node-${{ hashFiles('**/package-lock.json') }}
        # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        restore-keys: |
          node-
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: actions/upload-artifact@v4.4.3
      with:
        # Artifact name
        name: test-coverage-${{ matrix.node-version }}
        # A file, directory or wildcard pattern that describes what to upload
        path: coverage
